// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebNet23Online.Data;

#nullable disable

namespace WebNet23Online.Data.Migrations
{
    [DbContext(typeof(WebContext))]
    partial class WebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeDataAnimeGirlData", b =>
            {
                b.Property<int>("AnimesId")
                    .HasColumnType("int");

                b.Property<int>("HeroesId")
                    .HasColumnType("int");

                b.HasKey("AnimesId", "HeroesId");

                b.HasIndex("HeroesId");

                b.ToTable("AnimeDataAnimeGirlData");
            });

            modelBuilder.Entity("UserDataUserData", b =>
            {
                b.Property<int>("MyFriendsId")
                    .HasColumnType("int");

                b.Property<int>("WhoIsMyFriendsId")
                    .HasColumnType("int");

                b.HasKey("MyFriendsId", "WhoIsMyFriendsId");

                b.HasIndex("WhoIsMyFriendsId");

                b.ToTable("UserDataUserData");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CoverUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("StudioId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("StudioId");

                b.ToTable("Animes");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeGirlData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("AnimeGirls");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.LittleLemonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableTimesOnly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Occasion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationDateOnly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatingPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("littleLemonDatas");
                });


            modelBuilder.Entity("WebNet23Online.Data.Models.HabitData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnimeGirls");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeStudioData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("AnimeStudios");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.BeastData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("BeastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("BriefDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NativeRange")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Beasts");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.FoodItemData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ImgURL")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Ingredients")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MenuType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Price")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("FoodItems");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ColorOfDot")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DoneCount")
                    .HasColumnType("int");

                b.Property<int?>("HabitTrackerDataId")
                    .HasColumnType("int");

                b.Property<double>("Percent")
                    .HasColumnType("float");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("WeekResults")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("HabitTrackerDataId");

                b.ToTable("HabitData");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitTrackerData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("HabitTracker");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.MazeData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("MazeType")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Mazes");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandsData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("RockBand");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockLegendsData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("GroupNames")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Likes")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("RockLegends");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.GameData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Genre")
                    .HasColumnType("int");

                b.Property<string>("ImageUrl")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Games");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Role")
                    .HasColumnType("int");

                b.Property<int>("UserProfileId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserProfileId")
                    .IsUnique();

                b.ToTable("Users");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserProfileData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FavBook")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PetName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("UserProfileData");
            });

            modelBuilder.Entity("AnimeDataAnimeGirlData", b =>
            {
                b.HasOne("WebNet23Online.Data.Models.AnimeData", null)
                    .WithMany()
                    .HasForeignKey("AnimesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("WebNet23Online.Data.Models.AnimeGirlData", null)
                    .WithMany()
                    .HasForeignKey("HeroesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("UserDataUserData", b =>
            {
                b.HasOne("WebNet23Online.Data.Models.UserData", null)
                    .WithMany()
                    .HasForeignKey("MyFriendsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("WebNet23Online.Data.Models.UserData", null)
                    .WithMany()
                    .HasForeignKey("WhoIsMyFriendsId")
                    .OnDelete(DeleteBehavior.ClientCascade)
                    .IsRequired();
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeData", b =>
            {
                b.HasOne("WebNet23Online.Data.Models.AnimeStudioData", "Studio")
                    .WithMany("Animes")
                    .HasForeignKey("StudioId")
                    .OnDelete(DeleteBehavior.NoAction);


                b.Navigation("Studio");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitData", b =>
            {
                b.HasOne("WebNet23Online.Data.Models.HabitTrackerData", null)
                    .WithMany("Habits")
                    .HasForeignKey("HabitTrackerDataId");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
            {
                b.HasOne("WebNet23Online.Data.Models.UserProfileData", "UserProfile")
                    .WithOne("User")
                    .HasForeignKey("WebNet23Online.Data.Models.UserData", "UserProfileId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("UserProfile");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeStudioData", b =>
            {
                b.Navigation("Animes");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitTrackerData", b =>
            {
                b.Navigation("Habits");
            });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserProfileData", b =>
            {
                b.Navigation("User")
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
