//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.Steam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SteamShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SteamShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.Steam.SteamShared", typeof(SteamShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About company.
        /// </summary>
        public static string Footer_About_Company {
            get {
                return ResourceManager.GetString("Footer_About_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikita Corporation. All rights reserved. All trademarks are property of their respective owners..
        /// </summary>
        public static string Footer_bottom {
            get {
                return ResourceManager.GetString("Footer_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Footer_Jobs {
            get {
                return ResourceManager.GetString("Footer_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string Footer_Legal {
            get {
                return ResourceManager.GetString("Footer_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Footer_Privacy_Policy {
            get {
                return ResourceManager.GetString("Footer_Privacy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steamworks.
        /// </summary>
        public static string Footer_Steamworks {
            get {
                return ResourceManager.GetString("Footer_Steamworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Footer_Support {
            get {
                return ResourceManager.GetString("Footer_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Primary_Nav_About {
            get {
                return ResourceManager.GetString("Primary_Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Primary_Nav_Catalog {
            get {
                return ResourceManager.GetString("Primary_Nav_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Primary_Nav_Community {
            get {
                return ResourceManager.GetString("Primary_Nav_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Primary_Nav_Store {
            get {
                return ResourceManager.GetString("Primary_Nav_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Primary_Nav_Support {
            get {
                return ResourceManager.GetString("Primary_Nav_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All projects.
        /// </summary>
        public static string Top_Bar_All_Projects_Button {
            get {
                return ResourceManager.GetString("Top_Bar_All_Projects_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Steam.
        /// </summary>
        public static string Top_Bar_Install_Button {
            get {
                return ResourceManager.GetString("Top_Bar_Install_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Top_Bar_Login_Button {
            get {
                return ResourceManager.GetString("Top_Bar_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Top_Bar_Logout_Button {
            get {
                return ResourceManager.GetString("Top_Bar_Logout_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Top_Bar_Register_Button {
            get {
                return ResourceManager.GetString("Top_Bar_Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Top_Bar_Search_Button {
            get {
                return ResourceManager.GetString("Top_Bar_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the store.
        /// </summary>
        public static string Top_Bar_Search_Placeholder {
            get {
                return ResourceManager.GetString("Top_Bar_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Top_Bar_Welcome_Text {
            get {
                return ResourceManager.GetString("Top_Bar_Welcome_Text", resourceCulture);
            }
        }
    }
}
