//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorld {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorld() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld", typeof(AnimalWorld).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About our planet.
        /// </summary>
        public static string AboutPlanet {
            get {
                return ResourceManager.GetString("AboutPlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an animal family.
        /// </summary>
        public static string AddAnimalFamily {
            get {
                return ResourceManager.GetString("AddAnimalFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an animal species.
        /// </summary>
        public static string AddAnimalSpecies {
            get {
                return ResourceManager.GetString("AddAnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data.
        /// </summary>
        public static string AddData {
            get {
                return ResourceManager.GetString("AddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding animal data.
        /// </summary>
        public static string AddingAnimalData {
            get {
                return ResourceManager.GetString("AddingAnimalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding data.
        /// </summary>
        public static string AddingData {
            get {
                return ResourceManager.GetString("AddingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City, street, house.
        /// </summary>
        public static string AddressExample {
            get {
                return ResourceManager.GetString("AddressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add zoo.
        /// </summary>
        public static string AddZoo {
            get {
                return ResourceManager.GetString("AddZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amazing world of animals.
        /// </summary>
        public static string AmazingAnimalWorld {
            get {
                return ResourceManager.GetString("AmazingAnimalWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string AnimalFamilies {
            get {
                return ResourceManager.GetString("AnimalFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family of animal.
        /// </summary>
        public static string AnimalFamily {
            get {
                return ResourceManager.GetString("AnimalFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Cats.
        /// </summary>
        public static string AnimalFamilyExample {
            get {
                return ResourceManager.GetString("AnimalFamilyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key features of the family....
        /// </summary>
        public static string AnimalFamilySummary {
            get {
                return ResourceManager.GetString("AnimalFamilySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal species.
        /// </summary>
        public static string AnimalSpecies {
            get {
                return ResourceManager.GetString("AnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Forest cat.
        /// </summary>
        public static string AnimalSpeciesExample {
            get {
                return ResourceManager.GetString("AnimalSpeciesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the species.
        /// </summary>
        public static string AnimalSpeciesSummary {
            get {
                return ResourceManager.GetString("AnimalSpeciesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links between zoos and animal species.
        /// </summary>
        public static string AnimalSpeciesZoosLinks {
            get {
                return ResourceManager.GetString("AnimalSpeciesZoosLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up connections between parks and animal species.
        /// </summary>
        public static string AnimalSpeciesZoosLinksSetup {
            get {
                return ResourceManager.GetString("AnimalSpeciesZoosLinksSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of animals.
        /// </summary>
        public static string AnimalWorldTitle {
            get {
                return ResourceManager.GetString("AnimalWorldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the animal family.
        /// </summary>
        public static string ChooseAnimalFamily {
            get {
                return ResourceManager.GetString("ChooseAnimalFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the animal type.
        /// </summary>
        public static string ChooseAnimalSpecies {
            get {
                return ResourceManager.GetString("ChooseAnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select zoo.
        /// </summary>
        public static string ChooseZoo {
            get {
                return ResourceManager.GetString("ChooseZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; 2026 Animal World. Protect Nature!.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitat.
        /// </summary>
        public static string Habitat {
            get {
                return ResourceManager.GetString("Habitat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: the territory of Europe and Asia Minor.
        /// </summary>
        public static string HabitatExample {
            get {
                return ResourceManager.GetString("HabitatExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Earth is home to millions of amazing creatures, from tiny insects to giant blue whales..
        /// </summary>
        public static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting facts.
        /// </summary>
        public static string Interesting {
            get {
                return ResourceManager.GetString("Interesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data on animals yet..
        /// </summary>
        public static string NoAnimalFamilies {
            get {
                return ResourceManager.GetString("NoAnimalFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data on animal species yet..
        /// </summary>
        public static string NoAnimalSpecies {
            get {
                return ResourceManager.GetString("NoAnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data on zoos yet.
        /// </summary>
        public static string NoZoos {
            get {
                return ResourceManager.GetString("NoZoos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string OnIndex {
            get {
                return ResourceManager.GetString("OnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLink {
            get {
                return ResourceManager.GetString("SaveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what information you want to add.
        /// </summary>
        public static string SelectInformationType {
            get {
                return ResourceManager.GetString("SelectInformationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select a zoo, then an animal species..
        /// </summary>
        public static string SelectZooThenAnimalSpecies {
            get {
                return ResourceManager.GetString("SelectZooThenAnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species name.
        /// </summary>
        public static string SpeciesName {
            get {
                return ResourceManager.GetString("SpeciesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoo.
        /// </summary>
        public static string Zoo {
            get {
                return ResourceManager.GetString("Zoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Singapore Zoo.
        /// </summary>
        public static string ZooExample {
            get {
                return ResourceManager.GetString("ZooExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the zoo.
        /// </summary>
        public static string ZooName {
            get {
                return ResourceManager.GetString("ZooName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoos.
        /// </summary>
        public static string Zoos {
            get {
                return ResourceManager.GetString("Zoos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of zoos.
        /// </summary>
        public static string ZoosList {
            get {
                return ResourceManager.GetString("ZoosList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefly about the zoo....
        /// </summary>
        public static string ZooSummary {
            get {
                return ResourceManager.GetString("ZooSummary", resourceCulture);
            }
        }
    }
}
