//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JapaneseDomesticMarket {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JapaneseDomesticMarket() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.JapaneseDomesticMarket", typeof(JapaneseDomesticMarket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More details.
        /// </summary>
        public static string Catalog_Button_More_Details {
            get {
                return ResourceManager.GetString("Catalog_Button_More_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of cars without inspection histories.
        /// </summary>
        public static string Catalog_Statistics_VehicalHistory {
            get {
                return ResourceManager.GetString("Catalog_Statistics_VehicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach a photo.
        /// </summary>
        public static string CreateCars_Attach_Photo {
            get {
                return ResourceManager.GetString("CreateCars_Attach_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brand.
        /// </summary>
        public static string CreateCars_Brand {
            get {
                return ResourceManager.GetString("CreateCars_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vehicle inspection history.
        /// </summary>
        public static string CreateCars_Headers_Vehicle_Inspection_History {
            get {
                return ResourceManager.GetString("CreateCars_Headers_Vehicle_Inspection_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer.
        /// </summary>
        public static string CreateCars_Manufacturer {
            get {
                return ResourceManager.GetString("CreateCars_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model.
        /// </summary>
        public static string CreateCars_Model {
            get {
                return ResourceManager.GetString("CreateCars_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        public static string CreateCars_Send_Button {
            get {
                return ResourceManager.GetString("CreateCars_Send_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in to leave a comment..
        /// </summary>
        public static string Journal_Comments_Login {
            get {
                return ResourceManager.GetString("Journal_Comments_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на April 19, 2026.
        /// </summary>
        public static string Journal_Date_19_April {
            get {
                return ResourceManager.GetString("Journal_Date_19_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на August 30, 2025.
        /// </summary>
        public static string Journal_Date_30_August {
            get {
                return ResourceManager.GetString("Journal_Date_30_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s get acquainted!.
        /// </summary>
        public static string Journal_Header {
            get {
                return ResourceManager.GetString("Journal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments.
        /// </summary>
        public static string Journal_Post_Comment {
            get {
                return ResourceManager.GetString("Journal_Post_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hundreds of participants and guests gathered on the grounds of Lida Castle to enjoy the festive atmosphere, see unique cars, and share experiences..
        /// </summary>
        public static string Journal_Text_Lida_1 {
            get {
                return ResourceManager.GetString("Journal_Text_Lida_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It was noisy! It was smoky! It was awesome! I declare the drift season officially open! I don&apos;t know how many sets of tires the guys had to change during all the runs, but the fact is that tires and wheels flew off today!.
        /// </summary>
        public static string Journal_Text_Raubichi_1 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bumpers and hoods flew off... Some pilots got too close to the walls and concrete blocks..
        /// </summary>
        public static string Journal_Text_Raubichi_2 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Photos can&apos;t capture the full furor; one can only try. So, I&apos;m sharing my favorite photos..
        /// </summary>
        public static string Journal_Text_Raubichi_3 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Once upon a time, when I took a test, I could recognize more than 180 car logos..
        /// </summary>
        public static string Journal_Text_Test_Models {
            get {
                return ResourceManager.GetString("Journal_Text_Test_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на P.S. This is a skill that I have never needed in life yet..
        /// </summary>
        public static string Journal_Text_Test_Models_h2 {
            get {
                return ResourceManager.GetString("Journal_Text_Test_Models_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opening of the 2026 drift season, Raubichi.
        /// </summary>
        public static string Journal_Title_Header {
            get {
                return ResourceManager.GetString("Journal_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cars Picnic in Lida.
        /// </summary>
        public static string Journal_Title_Header_2 {
            get {
                return ResourceManager.GetString("Journal_Title_Header_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The motivation for creating this online portal was my love for JDM culture and the atmosphere that reigns at car gatherings..
        /// </summary>
        public static string Journal_Welcome_Line {
            get {
                return ResourceManager.GetString("Journal_Welcome_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advertisements.
        /// </summary>
        public static string Layout_Jdm_Header_Advertisements {
            get {
                return ResourceManager.GetString("Layout_Jdm_Header_Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Layout_Jdm_Header_Home {
            get {
                return ResourceManager.GetString("Layout_Jdm_Header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Journal.
        /// </summary>
        public static string Layout_Jdm_Header_Journal {
            get {
                return ResourceManager.GetString("Layout_Jdm_Header_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sell ​​car.
        /// </summary>
        public static string Layout_Jdm_Header_Sell_Car {
            get {
                return ResourceManager.GetString("Layout_Jdm_Header_Sell_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No civics on my site..
        /// </summary>
        public static string Validation_attribute_civic {
            get {
                return ResourceManager.GetString("Validation_attribute_civic", resourceCulture);
            }
        }
    }
}
