//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RockLegendsPortal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RockLegendsPortal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.RockLegendsPortal", typeof(RockLegendsPortal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder from Australia, the living embodiment of the phrase &quot;high voltage.&quot;
        ///AC/DC is a band that hasn&apos;t changed its style for decades because their rock &apos;n&apos; roll is perfect.
        ///Since 1973, the Young brothers have been creating music that makes you can&apos;t stand still. The grimy sound of Angus Young&apos;s Gibson SG and his unchanging school uniform have become the hallmarks of stadium-level excitement.
        ///Their rhythm section works like a Swiss watch, and their vocals pierce any wall. Through vocalist changes
        ///and tr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ACDC_info {
            get {
                return ResourceManager.GetString("ACDC-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The leading chameleons of the modern heavy metal scene, having evolved from harsh deathcore to a futuristic rock sound. Oliver Sykes and his band
        ///from Sheffield have never been afraid to experiment, blending metal with electronics, pop, and orchestras. They have become a symbol of evolution,
        ///constantly challenging expectations and creating trends that the world follows. Their show is a high-tech immersion into a world of visual
        ///art and powerful sound, where old hits sit alongside cutting-edge composition [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BMTH_info {
            get {
                return ResourceManager.GetString("BMTH_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadium rock heroes from New Jersey, who conquered the world with their sincerity and flawless melodies.
        ///Jon Bon Jovi and his band proved that rock can be not only heavy, but also incredibly soulful.
        ///In the &apos;80s, they became a symbol of the era, combining the drive of glam rock with lyrics about the lives of ordinary guys and big dreams.
        ///Their ballads are sung by the whole world, and their action songs make entire cities jump. This is music about hope, love,
        ///and about never giving up, even if you&apos;re &quot;li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BonJovi_info {
            get {
                return ResourceManager.GetString("BonJovi_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll sell my soul for tickets to an AC/DC concert..
        /// </summary>
        public static string Easter_egg {
            get {
                return ResourceManager.GetString("Easter_egg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gods of thunder and rock &apos;n&apos; roll, bursting onto the stage in a cloud of fire and makeup.
        ///KISS isn&apos;t just a band, it&apos;s the greatest show on the planet, which began in New York City in 1973.
        ///Four guys—Demon, Starchild, E.T., and Cat—created an entire universe of heavy riffs,
        ///high platforms, and exploding pyrotechnics. Over the decades, they&apos;ve sold over 100 million albums,
        ///but their true element has always been in stadiums. Each of their performances is a ritual, where blood, fire, and guitars
        ///merge int [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KISS_info {
            get {
                return ResourceManager.GetString("KISS_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute titans who rewrote the rules of heavy music and turned thrash metal into a global phenomenon. Emerging from the garages of San Francisco in the early &apos;80s,
        ///Hetfield and Ulrich created the foundation upon which the entire modern scene stands. Their journey is a story of overcoming, tragedy, and resounding victories,
        ///cementing their status as the planet&apos;s premier metal band. From furious, high-speed thrashers to profound ballads, their music penetrates the very essence
        ///of human rage and hope. Mill [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Metallica_info {
            get {
                return ResourceManager.GetString("Metallica_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Prince of Darkness, the great and terrible—the man who became synonymous with the word &quot;heavy metal.&quot;
        ///Ozzy&apos;s journey began in foggy Birmingham with Black Sabbath, where he laid the foundations for the darkest
        ///and heaviest sound in history. But his solo career proved that Ozzy&apos;s madness knows no bounds.
        ///Throughout his ups and downs, he remains the &quot;iron man&quot; of the rock scene, whose voice is unmistakable.
        ///His charisma is simultaneously frightening and inspiring, and his concerts are always a balance  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ozzy_info {
            get {
                return ResourceManager.GetString("Ozzy_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The roar of a German industrial machine, merciless and uncompromising. Since 1994, six guys from
        ///East Berlin have been transforming music into a scorching fusion of metal, electronics, and pure fire. Till Lindemann and
        ///his team have created an aesthetic where provocation meets perfect sonic discipline. Their performances are more than just music; they are a total theater of pyrotechnics, where every riff is backed by a column of flame, and every word sinks
        ///into the consciousness with its weight. Monument [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Rammstein_info {
            get {
                return ResourceManager.GetString("Rammstein_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preachers of drive and powerful alternative rock, proving that bright energy can be truly heavy. Skillet is a
        ///unique fusion of hard guitar riffs, symphonic arrangements, and piercing male and female vocals. John Cooper and his
        ///band have created music that becomes an anthem for those seeking strength in the darkest times. Their songs are full of struggle, faith, and an unbreakable
        ///spirit, making every performance incredibly emotional and honest. Their incredible dedication on stage and connection with the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Skillet_info {
            get {
                return ResourceManager.GetString("Skillet_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine masks embodying the collective nightmare and primal chaos of Iowa. Slipknot burst onto the scene at the turn of the century, bringing with them an unprecedented level of aggression, percussive madness, and visual terror. They&apos;re not just a band, they&apos;re a cult, uniting &quot;maggots&quot; around the world under the banner of total self-expression and pain. Behind the terrifying imagery lies a masterful mastery of sound, where heaviness meets melody, and fury meets profound meaning. Each of their shows is a contr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Slipknot_info {
            get {
                return ResourceManager.GetString("Slipknot_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of these bands do you like the most?.
        /// </summary>
        public static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters of alternative rock from Canada, whose songs have become the voice of an entire generation experiencing internal turmoil.
        ///Three Days Grace masterfully convey feelings of pain, dependence, and the struggle to be oneself. Their music is built on honest
        ///lyrics and punchy choruses that make stadiums sing in unison. The change of vocalist only confirmed that the band&apos;s spirit
        ///is stronger than any circumstance, and their commitment to a hard and melodic sound remains unwavering. Each performance is an  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TDG_info {
            get {
                return ResourceManager.GetString("TDG_info", resourceCulture);
            }
        }
    }
}
