//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RockBand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RockBand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.RockBand", typeof(RockBand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to list.
        /// </summary>
        public static string Index_Add_Button {
            get {
                return ResourceManager.GetString("Index_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by user:.
        /// </summary>
        public static string Index_Add_By_User {
            get {
                return ResourceManager.GetString("Index_Add_By_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Index_Add_Card_Description {
            get {
                return ResourceManager.GetString("Index_Add_Card_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new card will appear in the list in the same format as the others..
        /// </summary>
        public static string Index_Add_Description {
            get {
                return ResourceManager.GetString("Index_Add_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefly about the band and its sound.
        /// </summary>
        public static string Index_Add_Description_Example {
            get {
                return ResourceManager.GetString("Index_Add_Description_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Index_Add_Genres {
            get {
                return ResourceManager.GetString("Index_Add_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a band.
        /// </summary>
        public static string Index_Add_Header {
            get {
                return ResourceManager.GetString("Index_Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a band photo or a link from the Internet.
        /// </summary>
        public static string Index_Add_Image {
            get {
                return ResourceManager.GetString("Index_Add_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the image&apos;s direct URL. This field can be left blank..
        /// </summary>
        public static string Index_Add_Image_Description {
            get {
                return ResourceManager.GetString("Index_Add_Image_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://site.com/path/to/photo.jpg.
        /// </summary>
        public static string Index_Add_Image_Example {
            get {
                return ResourceManager.GetString("Index_Add_Image_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Index_Add_Name {
            get {
                return ResourceManager.GetString("Index_Add_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, Arctic Monkeys.
        /// </summary>
        public static string Index_Add_Name_Example {
            get {
                return ResourceManager.GetString("Index_Add_Name_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add groups you need to.
        /// </summary>
        public static string Index_Add_Needed {
            get {
                return ResourceManager.GetString("Index_Add_Needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what you prefer:.
        /// </summary>
        public static string Index_ChooseGenres {
            get {
                return ResourceManager.GetString("Index_ChooseGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Index_Edit_Button {
            get {
                return ResourceManager.GetString("Index_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a band.
        /// </summary>
        public static string Index_Edit_Choose {
            get {
                return ResourceManager.GetString("Index_Edit_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing genres is only available to users with the band owner role..
        /// </summary>
        public static string Index_Edit_Error {
            get {
                return ResourceManager.GetString("Index_Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit genres of existing bands.
        /// </summary>
        public static string Index_Edit_Genres {
            get {
                return ResourceManager.GetString("Index_Edit_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a band, then select genres and click “Save”..
        /// </summary>
        public static string Index_Edit_Instruction {
            get {
                return ResourceManager.GetString("Index_Edit_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string Index_Edit_Log_In {
            get {
                return ResourceManager.GetString("Index_Edit_Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To edit genres you need to.
        /// </summary>
        public static string Index_Edit_Needed {
            get {
                return ResourceManager.GetString("Index_Edit_Needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Index_Edit_Or {
            get {
                return ResourceManager.GetString("Index_Edit_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string Index_Edit_Register {
            get {
                return ResourceManager.GetString("Index_Edit_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Index_Edit_Save_Button {
            get {
                return ResourceManager.GetString("Index_Edit_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My favorite bands.
        /// </summary>
        public static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music that inspires.
        /// </summary>
        public static string Index_Header_Description {
            get {
                return ResourceManager.GetString("Index_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Index_Header_Home {
            get {
                return ResourceManager.GetString("Index_Header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Index_Reset_button {
            get {
                return ResourceManager.GetString("Index_Reset_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Index_Show_Button {
            get {
                return ResourceManager.GetString("Index_Show_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite rock bands.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
    }
}
